### PR TITLE
Add tar task

### PR DESCRIPTION
**Pull request by pieces029**
- Created a task to bundle the eclipse tar.gz, fixing #81 
- Added tar.gz to be included in bintray. 
  - Unsure if this will effect how things are published to jcenter and central. I have only had archive type formats in there own repo in bintray.

### CODE REVIEW

**Comment by davidgyoung** [comment]
Nice to get rid of a shell script!  I will test tomorrow.

**Comment by davidgyoung** [comment]
Looks good.  I tested it an the generated .tar.gz file works as a library project in Eclipse.

One addition I would like to make is to *also* make a copy of the .aar file with the same version identifier in the filename, so I can easily upload this as a GitHub release, too.

What I get now is:

android-beacon-library						
android-beacon-library-debug.aar
android-beacon-library-2.1-beta3-7-g50c374f-SNAPSHOT.tar.gz
android-beacon-library-release.aar

What I would like is:

android-beacon-library						
android-beacon-library-debug.aar
android-beacon-library-2.1-beta3-7-g50c374f-SNAPSHOT.tar.gz
android-beacon-library-2.1-beta3-7-g50c374f-SNAPSHOT.aar
android-beacon-library-release.aar

I tried playing with the way you set it up to add this, but I can't seem to figure out how the filename name gets assigned to the .tar.gz file

**Comment by pieces029** [comment]
It's gradle wizardry. The tar task by default grabs that name from somewhere. I'll add another copy task so you get the output you want. I think I might move this stuff to a separate gradle file to try and keep the main one clean.

**Comment by pieces029** [comment]
Updated

**Pull request merged**
