### PR TITLE
Add Eddystone-EID support

### PR DESCRIPTION
**Pull request by davidgyoung**
- Add predefined constant for Eddystone-EID layout
- Add experimental class for resolving ephemeral IDs

### CODE REVIEW

**Comment by atotalnoob** [comment]
Would these changes support `eTLM` frames as well? 

I noticed on StackOverflow, you mentioned no one has tested these changes. I might be willing/able to test them out.

**Comment by davidgyoung** [comment]
> @davidgyoung Would these changes support `eTLM` frames as well?
> 
> I noticed on StackOverflow, you mentioned no one has tested these changes. I might be willing/able to test them out.

The ETLM frame was invented after this code was written, so these changes by themselves won't support ETLM, just Eddystone-EID.

**Comment by atotalnoob** [comment]
Thanks for the clarification. 

How would you gauge the level of effort to implement `eTLM`? What would be the level of effort for someone else who is not as familiar with your codebase to implement `eTLM`

Is there anything I need to test _specifically_ for this PR? Or just test in general?

**Comment by davidgyoung** [comment]
If you are an experienced and confident Android developer, I would estimate maybe 40 hours work to implement eTLM.  I would be happy to advise, but you'd need to do the coding and testing.

A prerequisite would be to build the eddystone-eid library branch  from source and get yourself an Android test app that resolves Eddystone-EID.  This itself might take a couple of days.  Eddystone EID is tricky and any little thing wrong will cause it to not work.  You must have a EID and eTLM compatible beacon that you can register and verify it works before you start anybody this.

**Comment by atotalnoob** [comment]
Unfortunately, I talked to the overlords, and they are putting this on the shelf for at least a few months. Just didn't want to leave you hanging

**Comment by davidgyoung** [comment]
Closing as Google no longer supports their trusted resolver making EID very difficult to use.

**Pull request closed without merging**
