### PR TITLE
Access persisted monitors

### PR DESCRIPTION
**Pull request by davidgyoung**
Fixes inability to read mo itored regions restored from persisted store after an app restart, as described in #441

### CODE REVIEW

**Comment by davidgyoung** [comment]
This is available for testing in a binary pre-release downloadable here: https://github.com/AltBeacon/android-beacon-library/releases/tag/2.9.2-beta2

**Comment by mmarshak** [comment]
Hi @davidgyoung, when do expect to release this change? Thanks

**Comment by mmarshak** [comment]
There is a problem with this change, it cause my app to crash.

I am using as reference the reference app with some changes.
I defined 2 regions  and let the app run in the foreground, upon the first time it detect the region it calls didEnterRegion() over there I trying yo get all the regions by doing -
ArrayList<Region> beaconRegions = (ArrayList<Region>) beaconManager.getMonitoredRegions();
And this is where is crash with -

E/AndroidRuntime: FATAL EXCEPTION: IntentService[BeaconIntentProcessor]
                  Process: org.altbeacon.beaconreference, PID: 32031
                  java.lang.ClassCastException: java.util.HashMap$KeySet cannot be cast to java.util.ArrayList
                      at org.altbeacon.beaconreference.BeaconReferenceApplication.didEnterRegion(BeaconReferenceApplication.java:244)
                      at org.altbeacon.beacon.BeaconIntentProcessor.onHandleIntent(BeaconIntentProcessor.java:88)
                      at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:158)
                      at android.os.HandlerThread.run(HandlerThread.java:61)

I tested in with Android M.
Bellow is the full log -
$ adb shell am start -n "org.altbeacon.beaconreference/org.altbeacon.beaconreference.MonitoringActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 32031 on device samsung-samsung_sm_j120a-4200dc21dc3353d3
W/System: ClassLoader referenced unknown path: /data/app/org.altbeacon.beaconreference-1/lib/arm
D/BeaconReferenceApp: I am back!!!!!
D/BeaconParser: Parsing beacon layout: m:2-3=beac,i:4-19,i:20-21,i:22-23,p:24-24,d:25-25
D/BeaconParser: Parsing beacon layout: m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24
D/BeaconReferenceApp: setting up background monitoring for beacons and power saving
D/BeaconManager: This consumer is not bound.  binding: org.altbeacon.beacon.startup.RegionBootstrap$InternalBeaconConsumer@6d6efcc
D/BeaconManager: consumer count is now: 1
D/AppStarter: Waiting for BeaconService connection
D/BeaconManager: This consumer is not bound.  binding: org.altbeacon.beacon.startup.RegionBootstrap$InternalBeaconConsumer@bb1831b
D/BeaconManager: consumer count is now: 2
D/AppStarter: Waiting for BeaconService connection
D/BeaconManager: This consumer is not bound.  binding: org.altbeacon.beaconreference.BeaconReferenceApplication@a5c7215
D/BeaconManager: consumer count is now: 3
D/MonitoringActivity: onCreate
D/SecWifiDisplayUtil: Metadata value : SecSettings2
D/ViewRootImpl: #1 mView = com.android.internal.policy.PhoneWindow$DecorView{7854445 V.E...... R.....I. 0,0-0,0}
D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: false
D/BackgroundPowerSaver: activity resumed: org.altbeacon.beaconreference.MonitoringActivity@24098cb active activities: 1
D/ViewRootImpl: #1 mView = com.android.internal.policy.PhoneWindow$DecorView{c1118a8 I.E...... R.....ID 0,0-0,0}
I/BeaconService: beaconService version 2.9.2-beta2 is starting up
D/BluetoothCrashResolver: constructed
W/BluetoothCrashResolver: Can't read macs from BluetoothCrashResolverState.txt
D/BluetoothCrashResolver: Read 0 Bluetooth addresses
D/BluetoothCrashResolver: started listening for BluetoothAdapter events
I/CycledLeScanner: This Android 5.0.  We are using new scanning APIs
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
D/ModelSpecificDistanceCalculator: Finding best distance calculator for 6.0.1, MMB29K, SAMSUNG-SM-J120A, samsung
D/AndroidModel: Score is 0 for LGE;Nexus 4;KOT49H;4.4.2 compared to samsung;SAMSUNG-SM-J120A;MMB29K;6.0.1
D/AndroidModel: Score is 0 for Motorola;XT1092;MPE24.49-18;6.0 compared to samsung;SAMSUNG-SM-J120A;MMB29K;6.0.1
D/AndroidModel: Score is 0 for XT1115;Moto X Pro;LXG22.67-7.1;5.0.2 compared to samsung;SAMSUNG-SM-J120A;MMB29K;6.0.1
D/AndroidModel: Score is 0 for LGE;Nexus 5;LPV79;4.4.2 compared to samsung;SAMSUNG-SM-J120A;MMB29K;6.0.1
W/ModelSpecificDistanceCalculator: Cannot find match for this device.  Using default
D/ModelSpecificDistanceCalculator: Finding best distance calculator for 6.0.1, MMB29K, SAMSUNG-SM-J120A, samsung
D/AndroidModel: Score is 0 for LGE;Nexus 4;KOT49H;4.4.2 compared to samsung;SAMSUNG-SM-J120A;MMB29K;6.0.1
D/AndroidModel: Score is 0 for Motorola;XT1092;MPE24.49-18;6.0 compared to samsung;SAMSUNG-SM-J120A;MMB29K;6.0.1
D/AndroidModel: Score is 0 for XT1115;Moto X Pro;LXG22.67-7.1;5.0.2 compared to samsung;SAMSUNG-SM-J120A;MMB29K;6.0.1
D/AndroidModel: Score is 0 for LGE;Nexus 5;LPV79;4.4.2 compared to samsung;SAMSUNG-SM-J120A;MMB29K;6.0.1
W/ModelSpecificDistanceCalculator: Cannot find match for this device.  Using default
D/BeaconService: No org.altbeacon.beacon.SimulatedScanData class exists.
I/BeaconService: starting with intent Intent { cmp=org.altbeacon.beaconreference/org.altbeacon.beacon.service.BeaconService }
I/BeaconService: binding
I/BeaconService: starting with intent Intent { cmp=org.altbeacon.beaconreference/org.altbeacon.beacon.service.BeaconService }
D/DistanceConfigFetcher: response code is 200
D/libEGL: eglInitialize EGLDisplay = 0xaf67a7cc
I/OpenGLRenderer: Initialized EGL, version 1.4
D/ModelSpecificDistanceCalculator: Successfully downloaded distance models from online database
I/ModelSpecificDistanceCalculator: Successfully saved new distance model file
D/ModelSpecificDistanceCalculator: Finding best distance calculator for 6.0.1, MMB29K, SAMSUNG-SM-J120A, samsung
D/AndroidModel: Score is 0 for XT1115;Moto X Pro;LXG22.67-7.1;5.0.2 compared to samsung;SAMSUNG-SM-J120A;MMB29K;6.0.1
D/AndroidModel: Score is 0 for LGE;Nexus 4;KOT49H;4.4.2 compared to samsung;SAMSUNG-SM-J120A;MMB29K;6.0.1
D/AndroidModel: Score is 0 for LGE;Nexus 5;LPV79;4.4.2 compared to samsung;SAMSUNG-SM-J120A;MMB29K;6.0.1
W/ModelSpecificDistanceCalculator: Cannot find match for this device.  Using default
I/ModelSpecificDistanceCalculator: Successfully updated distance model with latest from online database
D/mali_winsys: new_window_surface returns 0x3000,  [480x321]-format:1
D/mali_winsys: new_window_surface returns 0x3000,  [480x800]-format:1
D/BeaconManager: we have a connection to the service now
D/AppStarter: Activating background region monitoring
D/AppStarter: Activating background region monitoring
D/AppStarter: Background region monitoring activated for region id1: f7826da6-4fa2-4e98-8024-bc5b71e0893e id2: 37876 id3: 1
D/BeaconManager: Starting monitoring region id1: f7826da6-4fa2-4e98-8024-bc5b71e0893e id2: 37876 id3: 1 with uniqueID: backgroundRegion1
D/BeaconManager: callback packageName: org.altbeacon.beaconreference
D/MonitoringStatus: Not restoring monitoring state because it was recorded too many milliseconds ago: 1479839933279
D/EnterExit: did didDetermineStateForRegion region. Identifier = backgroundRegion1 UUID = f7826da6-4fa2-4e98-8024-bc5b71e0893e Major = 37876 Minor = 1 state =0
D/BeaconManager: we have a connection to the service now
D/BeaconManager: we have a connection to the service now
D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 36 - 0, 0) vi=Rect(0, 36 - 0, 0) or=1
I/BeaconService: start monitoring received
D/BeaconService: startMonitoring called
D/MonitoringStatus: saveMonitoringStatusIfOn()
W/art: Suspending all threads took: 6.232ms
D/BeaconService: Currently monitoring 1 regions.
D/CycledLeScanner: start called
D/CycledLeScanner: starting a new scan cycle
D/CycledLeScanner: starting a new bluetooth le scan
D/CycledLeScanner: Waiting to stop scan cycle for another 1100 milliseconds
D/CycledLeScanner: Scan started
D/CycledLeScanner: Set scan periods called with 1100, 0 Background mode must have changed.
D/CycledLeScanner: We are not in the background.  Cancelling wakeup alarm
D/CycledLeScanner: cancel wakeup alarm: null
D/CycledLeScanner: Set a wakeup alarm to go off in 9223372036493943101 ms: PendingIntent{f76ffe0: android.os.BinderProxy@ee16299}
I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@e9479a time:61977593
D/CycledLeScanner: Waiting to stop scan cycle for another 99 milliseconds
D/CycledLeScanner: Done with scan cycle
D/CycledLeScanner: stopping bluetooth le scan
D/CycledLeScannerForLollipop: Stopping scan
D/CycledLeScannerForLollipop: Making new Android L scanner
D/BluetoothAdapter: STATE_ON
D/BluetoothAdapter: STATE_ON
D/CycledLeScanner: starting a new scan cycle
D/CycledLeScanner: starting a new bluetooth le scan
D/BluetoothAdapter: STATE_ON
D/CycledLeScanner: Waiting to stop scan cycle for another 1100 milliseconds
D/CycledLeScanner: Scan started
D/BluetoothAdapter: STATE_ON
D/BluetoothLeScanner: could not find callback wrapper
D/CycledLeScanner: Waiting to stop scan cycle for another 99 milliseconds
D/CycledLeScanner: Done with scan cycle
D/CycledLeScanner: stopping bluetooth le scan
D/CycledLeScannerForLollipop: Stopping scan
D/CycledLeScanner: starting a new scan cycle
D/BluetoothAdapter: STATE_ON
D/CycledLeScanner: starting a new bluetooth le scan
D/BluetoothAdapter: STATE_ON
D/BluetoothLeScanner: could not find callback wrapper
D/CycledLeScanner: Waiting to stop scan cycle for another 1100 milliseconds
D/CycledLeScanner: Scan started
D/ViewRootImpl: ViewPostImeInputStage processPointer 0
D/ViewRootImpl: ViewPostImeInputStage processPointer 1
D/ViewRootImpl: #3 mView = null
E/ViewRootImpl: sendUserActionEvent() mView == null
D/BackgroundPowerSaver: activity paused: org.altbeacon.beaconreference.MonitoringActivity@24098cb active activities: 0
D/BackgroundPowerSaver: setting background mode
D/BeaconManager: updating background flag to true
D/BeaconManager: updating scan period to 1000, 5000
I/BeaconService: set scan intervals received
D/CycledLeScanner: Set scan periods called with 1000, 5000 Background mode must have changed.
D/CycledLeScanner: We are in the background.  Setting wakeup alarm
D/CycledLeScanner: Set a wakeup alarm to go off in 300000 ms: PendingIntent{f76ffe0: android.os.BinderProxy@ee16299}
I/CycledLeScanner: Adjusted scanStopTime to be 360835926
D/CycledLeScanner: Done with scan cycle
D/CycledLeScanner: stopping bluetooth le scan
D/CycledLeScannerForLollipop: Stopping scan
D/CycledLeScanner: Normalizing between scan period from 5000 to 3071
D/BluetoothAdapter: STATE_ON
D/CycledLeScannerForLollipop: This is Android L. Doing a filtered scan for the background.
D/BluetoothAdapter: STATE_ON
D/BluetoothLeScanner: could not find callback wrapper
D/CycledLeScannerForLollipop: starting filtered scan in SCAN_MODE_LOW_POWER
D/ScanFilterUtils: Set up a scan filter: BluetoothLeScanFilter [mDeviceName=null, mDeviceAddress=null, mUuid=null, mUuidMask=null, mServiceDataUuid=null, mServiceData=null, mServiceDataMask=null, mManufacturerId=76, mManufacturerData=[2, 21], mManufacturerDataMask=[-1, -1]]
D/CycledLeScannerForLollipop: Waiting to start full Bluetooth scan for another 3071 milliseconds
D/BluetoothLeScanner: Start Scan
D/BluetoothAdapter: STATE_ON
D/BluetoothAdapter: STATE_ON
D/CycledLeScanner: Set a wakeup alarm to go off in 300000 ms: PendingIntent{f76ffe0: android.os.BinderProxy@ee16299}
D/BluetoothAdapter: STATE_ON
D/BluetoothAdapter: STATE_ON
D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=6
W/Binder: Caught a RuntimeException from the binder stub implementation.
          java.lang.SecurityException: Need ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to get scan results
              at android.os.Parcel.readException(Parcel.java:1620)
              at android.os.Parcel.readException(Parcel.java:1573)
              at android.bluetooth.IBluetoothGatt$Stub$Proxy.startScan(IBluetoothGatt.java:883)
              at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper.onClientRegistered(BluetoothLeScanner.java:375)
              at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:56)
              at android.os.Binder.execTransact(Binder.java:453)
V/ActivityThread: updateVisibility : ActivityRecord{2531d6a token=android.os.BinderProxy@e9479a {org.altbeacon.beaconreference/org.altbeacon.beaconreference.MonitoringActivity}} show : true
D/MonitoringActivity: coarse location permission granted
D/BeaconManager: updating background flag to false
D/BeaconManager: updating scan period to 1100, 0
D/BackgroundPowerSaver: activity resumed: org.altbeacon.beaconreference.MonitoringActivity@24098cb active activities: 1
I/BeaconService: set scan intervals received
D/CycledLeScanner: Set scan periods called with 1100, 0 Background mode must have changed.
D/CycledLeScanner: We are not in the background.  Cancelling wakeup alarm
D/CycledLeScanner: cancel wakeup alarm: PendingIntent{f76ffe0: android.os.BinderProxy@ee16299}
D/CycledLeScanner: Set a wakeup alarm to go off in 9223372036493939080 ms: PendingIntent{f76ffe0: android.os.BinderProxy@ee16299}
I/CycledLeScanner: Adjusted nextScanStartTime to be Tue Nov 22 13:38:56 EST 2016
I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@e9479a time:61981609
D/CycledLeScanner: starting a new scan cycle
D/CycledLeScanner: restarting a bluetooth le scan
D/CycledLeScannerForLollipop: starting non-filtered scan in SCAN_MODE_LOW_LATENCY
D/CycledLeScanner: Waiting to stop scan cycle for another 1100 milliseconds
D/CycledLeScanner: Scan started
D/CycledLeScanner: Waiting to stop scan cycle for another 99 milliseconds
D/BluetoothLeScanner: Start Scan
D/BluetoothAdapter: STATE_ON
D/BluetoothAdapter: STATE_ON
E/CycledLeScannerForLollipop: Scan Failed
D/CycledLeScanner: Done with scan cycle
D/CycledLeScanner: stopping bluetooth le scan
D/CycledLeScannerForLollipop: Stopping scan
D/CycledLeScanner: starting a new scan cycle
D/BluetoothAdapter: STATE_ON
D/CycledLeScanner: starting a new bluetooth le scan
D/BluetoothAdapter: STATE_ON
D/BluetoothLeScanner: Stop Scan
D/CycledLeScannerForLollipop: starting non-filtered scan in SCAN_MODE_LOW_LATENCY
D/CycledLeScanner: Waiting to stop scan cycle for another 1100 milliseconds
D/CycledLeScanner: Scan started
D/BluetoothLeScanner: Start Scan
D/BluetoothAdapter: STATE_ON
D/BluetoothAdapter: STATE_ON
D/BluetoothAdapter: STATE_ON
D/BluetoothAdapter: STATE_ON
D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=6
D/CycledLeScanner: Waiting to stop scan cycle for another 99 milliseconds
D/CycledLeScanner: Done with scan cycle
D/CycledLeScanner: stopping bluetooth le scan
D/CycledLeScannerForLollipop: Stopping scan
D/CycledLeScanner: starting a new scan cycle
D/BluetoothAdapter: STATE_ON
D/CycledLeScanner: starting a new bluetooth le scan
D/BluetoothAdapter: STATE_ON

**Comment by mmarshak** [comment]
I found the root cause and a solution,
The problem is the before the change the code was -

public Collection<Region> getMonitoredRegions() {		      public Collection<Region> getMonitoredRegions() {
 -        synchronized(this.monitoredRegions) {		 +        return MonitoringStatus.getInstanceForApplication(mContext).regions();
 -            return new ArrayList<Region>(this.monitoredRegions);		
 -        }		
      }

It was returning ArrayList, and with the new pull request it returns a Collection<Region>, as seen in -
public Collection<Region> getMonitoredRegions() {
 -        synchronized(this.monitoredRegions) {		 +        return MonitoringStatus.getInstanceForApplication(mContext).regions();

And you can not convert Collection to a List,
The solution is to do like before return instead of -
MonitoringStatus.getInstanceForApplication(mContext).regions();
return -
new ArrayList<region>(MonitoringStatus.getInstanceForApplication(mContext).regions());

After I corrected it a run few tests to make sure that the new functionality works.
I created initially 3 regions, and let it run for a while, then I stopped the app, change the code to create only one region instead of 3, and let it run and call getMonitoredRegions() which return 3 regions, which is great.

If you could fix the issue with the change and release as soon as you can not as an aar file it will be great.

**Comment by davidgyoung** [comment]
Hi, @mmarshak.  I'm not sure why the older code wrapped the collection of monitored regions in a new ArrayList before returning it, but since the method signature returns a Collection, I think the proper solution in your case is to simply wrap the returned value in a new ArrayList.  External code really should not depend on the internal implementation of the method allowing you to do a direct cast to a more specific collection type.

So you could simply change your code from:

     ArrayList beaconRegions = (ArrayList) beaconManager.getMonitoredRegions();

To:

     ArrayList beaconRegions = new ArrayList(beaconManager.getMonitoredRegions());

Glad to hear this change works for you.  The 2.9.2 release will probably come late next week.  You are welcome to use the beta2 binary until then.  I don't anticipate new changes going into a 2.9.2 release I am only waiting for some other test results to come in before making it official.

**Comment by mmarshak** [comment]
@davidgyoung this what I am doing today, my concern is that if some other people that use this method and expect to get ArrayList, with this change their code will break. Not a big deal, after they will build the code they will see the error and can fix it. You are right that it is better to clean the code.

Thank you allot for helping out!

**Pull request merged**
