### PR TITLE
Migrate library to Android X

### PR DESCRIPTION
**Pull request by paolorotolo**
Migrate library to Android X to allow seamlessly integration with new Android projects.

Note: ```doclava``` seems to be incompatible with latest Android X. Despite my effort to keep it in the library I had to remove the related gradle task. Also doclava latest release was published 5 years ago, I would consider moving on something more recent and well supported to generate javadocs.

### CODE REVIEW

**Comment by davidgyoung** [comment]
As a step along the way to this I have migrated to gradle 5.0 and removed the use of Doclava in #900.  I'd like to get rid of the remaining warnings before merging that.  Switching to Android X will come after that.  But such a switch may cause problems for folks who compile this library as a dependent project not yet converted to Android X (e.g the library reference project.)  The proper time to do that is open for discussion in #898

**Comment by paolorotolo** [comment]
Yes, you should specify in README the latest version compatible with support library (project that haven't migrated yet will still use it) and start releasing future updates to AndroidX only.

**Comment by paolorotolo** [comment]
As I wrote on #898, IMHO the switch is still important because the majority of apps is now migrating to AndroidX and having dependencies with support library (like alt-beacon library) forces them to use ```jetifier``` and refactor artifacts at build time.

**Comment by paolorotolo** [comment]
Hey @davidgyoung! Just seen your gradle PR merged #900.
I've updated my branch with latest master and fixed some conflicts. It should be ready to merge now.

**Comment by davidgyoung** [comment]
Ok, let me do some tests with the reference app before merging.

**Comment by paolorotolo** [comment]
@davidgyoung Any updates for this? We really need an Android X compatible version of this library :)

**Comment by davidgyoung** [comment]
Sorry, I actually merged this with master on Sep. 27 (and even issued a formal release 2.15.3) but apparently didn't push my changes to the server until now. :(

**Comment by paolorotolo** [comment]
Awesome, thank you.

**Pull request merged**
