### PR TITLE
Allow beacon transmission on Motorola devices

### PR DESCRIPTION
**Pull request by davidgyoung**
This addresses issue #134, which appears to be blocking beacon transmission on Motorola devices.

### CODE REVIEW

**Comment by mattwritescode** [comment]
The best changes seem to be short and simple like this one.

**Comment by davidgyoung** [comment]
Our friend at Motorola has confirmed that this makes transmission work on Moto G, Moto X,  and the new Moto E with 5.x.  

I'm going to roll a new release.  Can anybody check the Moto G in the office and see if a 5.x upgrade is available?  It is a first gen Moto G, not a second gen,  so I am not 100% sure it will work.

**Comment by davidhelms** [comment]
Sweet!

**Comment by jnebeker** [comment]
Just checked the Moto G, no update available

**Comment by davidgyoung** [comment]
Nuts

**Comment by davidgyoung** [comment]
Based on initial testing, this does allow Motorola devices to advertise.

**Pull request merged**
