### PR TITLE
proposal: make JobService's persist option configuable

### PR DESCRIPTION
**Pull request by hotchemi**
related: https://github.com/AltBeacon/android-beacon-library/issues/622

### Summary

There're some cases that we don't need to make the job persisted and `RECEIVE_BOOT_COMPLETED` permission(Not sure how many but at least in our use case it is).
This PR adds `jobPersistedEnabled` option as metadata for `BeaconService` as follows(defaults to true and it keeps backwards compatibility):

```xml
   <service android:name="org.altbeacon.beacon.service.BeaconService"
             tools:node="replace">
        <meta-data android:name="jobPersistedEnabled" android:value="false"/>
    </service>
```

~With this change, the flag would be `false` by default and you need to manually add the option to enable the persistent option.~
~I know breaking backwards compatibility should be avoided and would like to discuss it if you like the idea 🙇~ 

Thx in advance!

### CODE REVIEW

**Comment by hotchemi** [comment]
Could you take a look when you have time? 🙏

**Comment by hotchemi** [comment]
Hi~any update? 🙇

**Comment by davidgyoung** [comment]
Hi, @hotchemi.  Apologies, I misunderstood that a key part of this PR is to allow configuration in the manifest that the job is not persisted.  Because I did not understand this, I thought my last suggestion has resolved the issue for you.

Is there a reason that you need this configured in the manifest?  It seems it would be much simpler to have a method to configure this, say:

beaconManager.setJobPersistenceEnabled(false)

Then just set this once in your code if you do not want the default persisted jobs.

Ultimately the library is going to be moving to a new configuration API that is exclusively programmatic (not declared in the manifest), so this might be a better fit.    

Thoughts?

**Comment by hotchemi** [comment]
> Ultimately the library is going to be moving to a new configuration API that is exclusively programmatic (not declared in the manifest), so this might be a better fit.

@davidgyoung Thx for the feedback!

> Is there a reason that you need this configured in the manifest?

This is just to keep the API consistency with [longScanForcingEnabled](https://github.com/AltBeacon/android-beacon-library/pull/529) and I don't have a strong opinion around here🙂 But presumably we should follow after you accomplish migration to the new programmatic API?

We're using the forked version with this change and it's kinda not urgent now, it's also fine closing the PR and wait for your work👍

**Comment by davidgyoung** [comment]
@hotchemi please see the JobSchedulerScanStrategy section [here](https://github.com/AltBeacon/android-beacon-library/issues/1061).  Will this kind of API work for you?

**Comment by hotchemi** [comment]
@davidgyoung Thx, I checked the doc and `scheduledJobScanStrategy.jobPersistenceEnabled = true` looks good to me 👍

**Comment by hotchemi** [comment]
Then let me close the PR. thx!

**Pull request closed without merging**
