### PR TITLE
Fixed issue when scan job could restart every time when we have activity navigation

### PR DESCRIPTION
**Pull request by VolodaUa**
The fix fixes the issue when we have the scan job restarting every time during navigation (activity opening) in the app.

Background mode - is set only if the user puts the app in the background or it keeps the background when startMonitoring was called in Application.onCreate during app start(as designed for background scanning).
Foreground mode - is set only one time when app become foreground. Fixed also an issue when starting activity is like the facade to find the proper starting activity to proceed app starting.

Fixes: https://github.com/AltBeacon/android-beacon-library/issues/1194

### CODE REVIEW

**Comment by VolodaUa** [comment]
@davidgyoung  Please take a look 

Thanks a lot!

**Comment by VolodaUa** [comment]
I am thinking about using ProcessLifecycleOwner.get().getLifecycle() as it's more accurate that activities..

**Comment by VolodaUa** [comment]
Hi @davidgyoung 

Could you please prepare a beta version with this fix? I locally tested it a lot and it works.

**Comment by VolodaUa** [comment]
Hi @davidgyoung 

We tested this solution with QA for a while. The application faced this issue once we started using this library. The fix solved the problem and then the app worked well. No more complains. I had to use reflection to replace the affected class in the library with my own. It's not good, but it the solution for now.  
The application can't detect beacons after simple navigation.

Please let me know if I need to provide more information.

**Comment by davidgyoung** [comment]
Thank you @VolodaUa

**Pull request merged**
